export const ActionTypes = {
  //
  SET_USERS: "SET_USERS",
  SELECTED_USER: "SELECTED_USE",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
  REMOVE_USER: "REMOVE_USER",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  ///
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CART: "CART",
  REMOVE_CART_PRODUCT: "REMOVE_CART_PRODUCT",
};
